### ISSUE TITLE
Error unknow project (-1)

### ISSUE THREAD

**Issue by Szum123321** [Franckyi/CMPDL#17]
While trying to download any modpack i get error -1 Unknow project.
Error log:
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:214)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at com.github.franckyi.cmpdl.CurseMetaAPI.getProject(CurseMetaAPI.java:26)
	at com.github.franckyi.cmpdl.task.cursemeta.GetProjectTask.call0(GetProjectTask.java:18)
	at com.github.franckyi.cmpdl.task.cursemeta.GetProjectTask.call0(GetProjectTask.java:7)
	at com.github.franckyi.cmpdl.task.TaskBase.call(TaskBase.java:14)
	at com.github.franckyi.cmpdl.task.TaskBase.call(TaskBase.java:9)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by skyecodes** [comment]
I'm aware of the issue. CurseMeta staging API has broken and I have to switch to the Twitch App API. I'll try to fix ASAP.

**Comment by skyecodes** [comment]
Please see #12 for more info.
