### ISSUE TITLE
Pam's Harvestcraft fails to download, 400 Bad Request

### ISSUE THREAD

**Issue by roothorick** [Franckyi/CMPDL#5]
Relevant log output:

    java.io.IOException: Error 400 at https://addons.cursecdn.com/files/2428/363/Pam's HarvestCraft 1.10.2j.jar
    	at com.github.franckyi.cmpdl.task.CustomTask.getLocation(CustomTask.java:55)
    	at com.github.franckyi.cmpdl.task.CustomTask.crawl(CustomTask.java:41)
    	at com.github.franckyi.cmpdl.task.CustomTask.crawl(CustomTask.java:42)
    	at com.github.franckyi.cmpdl.task.DownloadModsTask$DownloadModTask.call0(DownloadModsTask.java:66)
    	at com.github.franckyi.cmpdl.task.DownloadModsTask$DownloadModTask.call0(DownloadModsTask.java:55)
    	at com.github.franckyi.cmpdl.task.CustomTask.call(CustomTask.java:17)
    	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.lang.Thread.run(Thread.java:748)

wget has no problem downloading the same URL:

    $ wget "https://addons.cursecdn.com/files/2428/363/Pam's HarvestCraft 1.10.2j.jar"
    --2018-04-04 17:41:03--  https://addons.cursecdn.com/files/2428/363/Pam's%20HarvestCraft%201.10.2j.jar
    Resolving addons.cursecdn.com (addons.cursecdn.com)... 104.16.84.211, 104.16.83.211, 104.16.85.211, ...
    Connecting to addons.cursecdn.com (addons.cursecdn.com)|104.16.84.211|:443... connected.
    HTTP request sent, awaiting response... 302 Moved Temporarily
    Location: https://files.forgecdn.net/files/2428/363/Pam's%20HarvestCraft%201.10.2j.jar [following]
    --2018-04-04 17:41:03--  https://files.forgecdn.net/files/2428/363/Pam's%20HarvestCraft%201.10.2j.jar
    Resolving files.forgecdn.net (files.forgecdn.net)... 52.204.248.175, 52.72.253.131
    Connecting to files.forgecdn.net (files.forgecdn.net)|52.204.248.175|:443... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: https://media.forgecdn.net/files/2428/363/Pam%27s+HarvestCraft+1.10.2j.jar [following]
    --2018-04-04 17:41:03--  https://media.forgecdn.net/files/2428/363/Pam%27s+HarvestCraft+1.10.2j.jar
    Resolving media.forgecdn.net (media.forgecdn.net)... 52.222.216.249
    Connecting to media.forgecdn.net (media.forgecdn.net)|52.222.216.249|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 3240818 (3.1M) [application/java-archive]
    Saving to: ‘Pam's HarvestCraft 1.10.2j.jar’
    
    Pam's HarvestCraft 1.10.2j 100%[=====================================>]   3.09M  9.47MB/s    in 0.3s    
    
    2018-04-04 17:41:04 (9.47 MB/s) - ‘Pam's HarvestCraft 1.10.2j.jar’ saved [3240818/3240818]

Perhaps the quote isn't escaped correctly?

**Comment by skyecodes** [comment]
Won't fix for 2.0.0 release. Sorry for the inconvenience.
It will be fixed for 2.1.0 beta.
